import { NativeModules, Platform } from "react-native"
import { Circuit, PackagedCircuit, Parameter, ParameterType } from "@zkpassport/utils"
import { base64ToHex } from "./index"
const { NoirModule: Noir } = NativeModules

// Proof queue in memory to avoid concurrent proof generation
let proofQueue: Promise<void> = Promise.resolve()

const enqueueProof = <T,>(task: () => Promise<T>): Promise<T> => {
  const run = proofQueue.then(() => task())

  // Queue continues even if old one rejects
  proofQueue = run.then(
    () => {},
    () => {},
  )

  return run
}

/**
 * Load the SRS from the resources into the internal storage
 * so it can be used for proof generation and verification
 * Only needed for Android.
 * This assumes the SRS is in the /android/app/src/main/res/raw folder
 * otherwise it does nothing and the SRS will be downloaded on the fly
 * from Aztec's server
 */
export async function prepareSrs() {
  // Only needed for Android
  if (Platform.OS === "android") {
    await Noir.prepareSrs()
  }
}

/**
 * Deserialize a circuit from the JSON manifest file
 * and setup the SRS for this circuit
 * @param circuit The circuit to setup
 * @param lowMemoryMode Whether to use low memory mode
 * @returns The ID of the circuit
 */
export async function setupCircuit(circuit: PackagedCircuit, lowMemoryMode: boolean = false) {
  const { circuitId } = await enqueueProof<{ circuitId: string }>(() =>
    Noir.setupCircuit(
      JSON.stringify(circuit),
      // Default to subgroup 2^20 if size is not provided
      // We set the minimum size to 500000 (in subgroup 2^19) to avoid issues as the
      // gate count computation by bb gates is not correct
      Math.max(500000, circuit.size ?? 1000000),
      lowMemoryMode,
    ),
  )
  return circuitId as string
}

function computeInputArraySize(type: ParameterType) {
  let count = 0
  if (type.type && type.type.kind === "array") {
    count += (type.length || 0) * computeInputArraySize(type.type)
  } else {
    count += type.length || 0
  }
  return count
}

function computePublicInputsSize(params: Parameter[]) {
  let fieldCount = 0
  for (let param of params) {
    if (param.visibility === "private") {
      continue
    }
    if (param.type.kind === "array") {
      fieldCount += computeInputArraySize(param.type)
    } else if (param.type.kind === "string") {
      fieldCount += param.type.length || 0
    } else if (param.type.kind === "struct") {
      fieldCount += computePublicInputsSize(param.type.fields!)
    } else {
      fieldCount += 1
    }
  }
  return fieldCount
}

function getLastIndexOfPublicInputs(circuit: Circuit | PackagedCircuit) {
  // Each field is encoded as a hexadecimal string of 64 characters (i.e. 32 bytes).
  // After stripping the 4-byte noir_rs prefix in generateProof, the layout is:
  //   [N public inputs][proof body]
  return 64 * 3 + computePublicInputsSize(circuit.abi.parameters) * 64
}

/**
 * **WARNING: Not guaranteed to work with Honk proofs for now**
 *
 * Extract the public inputs from the proofs
 * @param circuit The circuit the proof is associated with
 * @param proofWithPublicInputs The proof containing the public inputs
 * @returns The raw public inputs
 */
export function extractRawPublicInputs(
  circuit: Circuit | PackagedCircuit,
  proofWithPublicInputs: string,
) {
  const lastIndex = getLastIndexOfPublicInputs(circuit)
  return proofWithPublicInputs.slice(64 * 3, lastIndex)
}

/**
 * **WARNING: Not guaranteed to work with Honk proofs for now**
 *
 * Extract the proof from the proof including public inputs by getting
 * rid of the public inputs
 * @param circuit The circuit the proof is associated with
 * @param proofWithPublicInputs The proof containing the public inputs
 * @returns The proof
 */
export function extractProof(circuit: Circuit | PackagedCircuit, proofWithPublicInputs: string) {
  const lastIndex = getLastIndexOfPublicInputs(circuit)
  return proofWithPublicInputs.slice(0, 64 * 3) + proofWithPublicInputs.slice(lastIndex)
}

/**
 * Generate a proof for the given inputs and circuit
 * @param inputs The inputs to the circuit
 * @param circuit If not preloaded, provide the JSON manifest file of the Noir circuit generated by nargo
 * @param vk The verification key of the circuit
 * @returns The proof
 */
export async function generateProof(inputs: { [key: string]: any }, circuitId: string, vk: string) {
  const { proof } = await enqueueProof<{ proof: string }>(() =>
    Noir.prove(inputs, circuitId, base64ToHex(vk)),
  )

  // noir_rs prepends a 4-byte (8 hex chars) BE u32 of num_public_inputs to its output.
  // We strip it so the proof matches the raw bb CLI layout used by cloud-prover:
  //   [public_inputs...][proof_body...]
  return {
    // This is the full proof, including the public inputs
    proofWithPublicInputs: proof.slice(8),
  }
}

/**
 * Verify a proof using the given verification key
 * @param proofWithPublicInputs The proof (including public inputs) to verify
 * @param circuit If not loaded before, either with the preloading function or the prove function,
 * then make sure to provide the JSON manifest file of the Noir circuit generated by nargo
 * @param vk The verification key of the circuit
 * @returns Whether the proof is valid
 */
export async function verifyProof(proofWithPublicInputs: string, circuitId: string, vk: string) {
  const { verified } = await Noir.verify(proofWithPublicInputs, circuitId, base64ToHex(vk))
  return verified
}

export async function execute(inputs: { [key: string]: any }, circuitId: string) {
  const { witness } = await Noir.execute(inputs, circuitId)
  return witness as string[]
}

/**
 * Remove a previously setup circuit from memory
 * @param circuitId The ID of the circuit to remove from memory
 */
export async function clearCircuit(circuitId: string) {
  await Noir.clearCircuit(circuitId)
}

/**
 * Remove all previously setup circuits from memory
 */
export async function clearAllCircuits() {
  await Noir.clearAllCircuits()
}
