import { StyleSheet } from "react-native"

export const INFO_ICON_COLOR = "#60B3FF"

export const scanPassportStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#07245C",
  },
  scrollContainer: {
    flex: 1,
  },
  scrollContent: {
    paddingTop: 20,
    paddingBottom: 20,
  },
  bottomContainer: {
    paddingTop: 20,
    paddingBottom: 20,
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.1)",
    backgroundColor: "#07245C",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 10,
  },
  title: {
    fontSize: 26,
    fontWeight: "700",
    textAlign: "center",
    marginVertical: 16,
    color: "white",
    // fontFamily: "Metropolis",
    letterSpacing: 0.7,
    textShadowColor: "rgba(0, 0, 0, 0.3)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  videoContainer: {
    borderRadius: 16,
    overflow: "hidden",
    marginHorizontal: 16,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  video: {
    width: "100%",
    aspectRatio: 16 / 9,
  },
  instructionsContainer: {
    padding: 20,
    marginTop: 10,
  },
  instructions: {
    fontSize: 17,
    marginBottom: 12,
    color: "#F0F4FF",
    // fontFamily: "Metropolis",
    lineHeight: 24,
    letterSpacing: 0.4,
    fontWeight: "400",
  },
  instructionsHighlight: {
    fontSize: 17,
    marginTop: 10,
    color: "#60B3FF",
    // fontFamily: "Metropolis",
    fontWeight: "700",
    lineHeight: 24,
    letterSpacing: 0.5,
  },
  bold: {
    fontWeight: "bold",
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  button: {
    width: 160,
    height: 50,
    borderRadius: 25,
    overflow: "hidden",
    elevation: 4,
    shadowColor: "#1E69FF",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
    backgroundColor: "#1E69FF",
    justifyContent: "center",
    alignItems: "center",
  },
  buttonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "700",
    // fontFamily: "Metropolis",
    letterSpacing: 0.5,
  },
  backButton: {
    padding: 10,
  },
  backButtonText: {
    color: "#E0E6FF",
    fontSize: 16,
    fontWeight: "600",
    // fontFamily: "Metropolis",
    letterSpacing: 0.3,
  },
  camera: {
    width: "100%",
    aspectRatio: 16 / 9,
  },
  stepsList: {
    gap: 16,
  },
  stepItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  stepNumber: {
    fontSize: 16,
    fontWeight: "700",
    color: "#60B3FF",
    // fontFamily: "Metropolis",
    backgroundColor: "rgba(96, 179, 255, 0.15)",
    width: 28,
    height: 28,
    textAlign: "center",
    textAlignVertical: "center",
    borderRadius: 14,
    lineHeight: 28,
  },
  stepText: {
    fontSize: 16,
    color: "#F0F4FF",
    // fontFamily: "Metropolis",
    lineHeight: 22,
    letterSpacing: 0.4,
    fontWeight: "400",
    flex: 1,
  },
  documentTypeContainer: {
    flexDirection: "row",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 12,
    marginTop: 16,
    marginHorizontal: 16,
    padding: 4,
  },
  documentTypeButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: "center",
  },
  documentTypeButtonActive: {
    backgroundColor: "#1E69FF",
    shadowColor: "#1E69FF",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  documentTypeText: {
    fontSize: 16,
    // fontFamily: "Metropolis",
    fontWeight: "600",
    color: "#B8C5E0",
  },
  documentTypeTextActive: {
    color: "white",
    fontWeight: "700",
  },
  helpButton: {
    flexDirection: "row",
    gap: 4,
    alignItems: "center",
    marginTop: 25,
  },
  helpButtonText: {
    fontSize: 13,
    color: "#60B3FF",
    // fontFamily: "Metropolis",
    fontWeight: "300",
    letterSpacing: 0.3,
  },
  modalOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  modalContainer: {
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalContent: {
    backgroundColor: "#0A2A5C",
    borderRadius: 16,
    padding: 24,
    maxWidth: 340,
    width: "100%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
    borderWidth: 1,
    borderColor: "rgba(96, 179, 255, 0.2)",
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "white",
    // fontFamily: "Metropolis",
    textAlign: "center",
    marginBottom: 16,
    letterSpacing: 0.5,
  },
  modalText: {
    fontSize: 16,
    color: "#F0F4FF",
    // fontFamily: "Metropolis",
    lineHeight: 24,
    textAlign: "left",
    marginBottom: 24,
    letterSpacing: 0.3,
    fontWeight: "400",
  },
  modalButton: {
    backgroundColor: "#1E69FF",
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 24,
    alignItems: "center",
    shadowColor: "#1E69FF",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 4,
  },
  modalButtonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "700",
    // fontFamily: "Metropolis",
    letterSpacing: 0.5,
  },
  manualEditorContainer: {
    backgroundColor: "#0A2A5C",
    borderRadius: 20,
    padding: 28,
    maxWidth: 380,
    width: "90%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.4,
    shadowRadius: 16,
    elevation: 12,
    borderWidth: 1,
    borderColor: "rgba(96, 179, 255, 0.3)",
  },
  manualEditorHeader: {
    marginBottom: 24,
    alignItems: "center",
  },
  manualEditorTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: "white",
    // fontFamily: "Metropolis",
    textAlign: "center",
    marginBottom: 8,
    letterSpacing: 0.6,
  },
  manualEditorSubtitle: {
    fontSize: 16,
    color: "#B8C5E0",
    // fontFamily: "Metropolis",
    textAlign: "center",
    fontWeight: "400",
    lineHeight: 22,
  },
  formContainer: {
    marginBottom: 28,
  },
  inputGroup: {
    marginBottom: 24,
  },
  inputLabel: {
    fontSize: 16,
    fontWeight: "700",
    color: "#60B3FF",
    // fontFamily: "Metropolis",
    marginBottom: 10,
    letterSpacing: 0.4,
  },
  inputWrapper: {
    backgroundColor: "rgba(30, 105, 255, 0.15)",
    borderRadius: 14,
    borderWidth: 2,
    borderColor: "rgba(30, 105, 255, 0.3)",
    position: "relative",
  },
  textInput: {
    color: "white",
    fontSize: 16,
    // fontFamily: "Metropolis",
    paddingVertical: 14,
    paddingHorizontal: 16,
    fontWeight: "500",
    letterSpacing: 0.3,
  },
  textInputError: {
    borderColor: "#FF3B3B",
    backgroundColor: "rgba(255, 59, 59, 0.1)",
  },
  errorText: {
    color: "#FF6B6B",
    fontSize: 13,
    marginTop: 6,
    // fontFamily: "Metropolis",
    fontWeight: "500",
  },
  manualEditorButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 16,
  },
  cancelButton: {
    flex: 1,
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 14,
    backgroundColor: "rgba(255, 59, 59, 0.15)",
    borderWidth: 2,
    borderColor: "rgba(255, 59, 59, 0.3)",
    alignItems: "center",
  },
  cancelButtonText: {
    color: "#FF6B6B",
    fontSize: 16,
    fontWeight: "700",
    // fontFamily: "Metropolis",
    letterSpacing: 0.5,
  },
  confirmButton: {
    flex: 1,
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 14,
    backgroundColor: "#1E69FF",
    alignItems: "center",
    shadowColor: "#1E69FF",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  confirmButtonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "700",
    // fontFamily: "Metropolis",
    letterSpacing: 0.5,
  },
  invalidMrzContainer: {
    padding: 20,
    backgroundColor: "rgba(255, 59, 59, 0.1)",
    borderRadius: 12,
    marginTop: 16,
    marginHorizontal: 16,
    borderWidth: 1,
    borderColor: "rgba(255, 59, 59, 0.3)",
  },
  invalidMrzText: {
    fontSize: 16,
    color: "#FF6B6B",
    // fontFamily: "Metropolis",
    marginBottom: 12,
    textAlign: "center",
    fontWeight: "600",
  },
  manualEntryButton: {
    backgroundColor: "#1E69FF",
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignItems: "center",
    shadowColor: "#1E69FF",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  manualEntryButtonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "700",
    // fontFamily: "Metropolis",
    letterSpacing: 0.5,
  },
  requiredAsterisk: {
    color: "#FF3B3B",
    fontSize: 16,
    fontWeight: "700",
  },
  dateHelper: {
    position: "absolute",
    right: 16,
    top: "50%",
    transform: [{ translateY: -8 }],
    color: "#60B3FF",
    fontSize: 12,
    fontWeight: "600",
    // fontFamily: "Metropolis",
    backgroundColor: "rgba(7, 36, 92, 0.8)",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
  },
  strugglingMrzContainer: {
    padding: 20,
    backgroundColor: "rgba(255, 193, 7, 0.1)",
    borderRadius: 12,
    marginTop: 16,
    marginHorizontal: 16,
    borderWidth: 1,
    borderColor: "rgba(255, 193, 7, 0.4)",
  },
  strugglingMrzText: {
    fontSize: 16,
    color: "#FFC107",
    // fontFamily: "Metropolis",
    marginBottom: 12,
    textAlign: "center",
    fontWeight: "600",
  },
  biometricIconDisplay: {
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
  },
  biometricIcon: {
    width: 40,
    height: 40,
  },
  iconContainer: {
    alignItems: "center",
    justifyContent: "center",
    width: 70,
    height: 70,
    borderRadius: 50,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
  },
  passportIcon: {
    fontSize: 40,
    color: "#60B3FF",
  },
  chipIconOverlay: {
    fontSize: 20,
    color: "rgba(255, 255, 255, 0.5)",
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    textAlign: "center",
    textAlignVertical: "center",
  },

  textButton: {
    paddingVertical: 12,
    alignItems: "center",
    marginTop: 16,
  },
  textButtonText: {
    color: "#B8C5E0",
    fontSize: 16,
    fontWeight: "600",
    // fontFamily: "Metropolis",
    letterSpacing: 0.3,
  },
  chipLocationInfo: {
    backgroundColor: "rgba(96, 179, 255, 0.15)",
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "rgba(96, 179, 255, 0.3)",
  },
  chipLocationTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: "#60B3FF",
    // fontFamily: "Metropolis",
    textAlign: "center",
    letterSpacing: 0.4,
  },
})
